"""First commit

Revision ID: 0aa26ccfad87
Revises: 4eaca9168955
Create Date: 2022-09-21 13:05:17.866779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa26ccfad87'
down_revision = '4eaca9168955'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salon', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'salon', 'employee', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salon', type_='foreignkey')
    op.drop_column('salon', 'employee_id')
    # ### end Alembic commands ###
