"""First commit

Revision ID: 10303531ffe7
Revises: f4ec3d0daca0
Create Date: 2022-09-19 22:42:25.840314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10303531ffe7'
down_revision = 'f4ec3d0daca0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
