"""First commit

Revision ID: e82693d98be0
Revises: 5828efd7eddf
Create Date: 2022-09-20 17:20:20.988508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82693d98be0'
down_revision = '5828efd7eddf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
